image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$TRAVIS_BRANCH
  - bin/develop up --force

test_sanbox_true:
  stage: test
  variables:
    SANDBOX_MODE: 'True'
  script:
    - bin/py.test ./openprocurement/tender/cfaua/tests/ --cov=openprocurement.tender.cfaua


test_sanbox_not_true:
  stage: test
  variables:
    SANDBOX_MODE: ''
  script:
    - bin/py.test ./openprocurement/tender/cfaua/tests/ --cov=openprocurement.tender.cfaua